### ISSUE TITLE
ES6 with React and sample application fails due to missing index_template.html

### ISSUE THREAD

**Issue by timweightman** [odecee/generator-confit#20]
Similar to #19 . This issue relates to a React sample application and may have flow-on implications regarding possible routing libraries / etc.

If I get some time I might take a look at this and / or #19 

```
Confit App Generator
? Would you like to rebuild from the existing configuration in confit.json? No
? Choose a build-profile for your project Latest - Webpack-based build profile (23 Dec 2015)
? Use EditorConfig? Yes
Writing "app" using Webpack
Project Path Generator
? Use default/existing paths? Yes
Build CSS Generator
? Supports older browsers (i.e. less than IE10)? No
? Choose a CSS compiler stylus
Build JS Generator
? Source code language ES6
? Target output language ES5
? JavaScript Framework (optional) React (latest)
? Vendor scripts OR module-names to include (edit in confit.json): (No vendor scripts defined)
Build HTML Generator
? HTML source file extension? .html
Entry Point Generator
? Entry-points for the application (edit in confit.json): Entry Points
Dev Server Generator
? Server port 3000
? Server hostname localhost
? Server protocol https
Production Server Generator
? Server port 3000
? Server hostname localhost
? Server protocol https
Verify Generator
? JavaScript linting eslint
Sample App Generator
? Create a sample app? Yes
Writing Webpack buildAssets options
Writing Webpack buildCSS options
Writing Webpack buildJS options
Writing Webpack buildHTML options
Writing Webpack build options
Writing Webpack serverDev options
Writing Grunt serverProd options
Writing Webpack unit-test options
Writing Protractor browser-test options
Writing Grunt verify options
Writing Webpack sampleApp options

events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/timweightman/.nvm/versions/node/v4.2.6/lib/node_modules/generator-confit/lib/../buildTool/webpack/sampleApp/templates/es6react/index-template.html
    at EditionInterface.exports._copySingle (/Users/timweightman/.nvm/versions/node/v4.2.6/lib/node_modules/generator-confit/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/timweightman/.nvm/versions/node/v4.2.6/lib/node_modules/generator-confit/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at write (/Users/timweightman/.nvm/versions/node/v4.2.6/lib/node_modules/generator-confit/buildTool/webpack/sampleApp/sampleApp.js:74:13)
    at module.exports.confitGen.create.writing (/Users/timweightman/.nvm/versions/node/v4.2.6/lib/node_modules/generator-confit/generators/sampleApp/index.js:85:26)
    at Object.<anonymous> (/Users/timweightman/.nvm/versions/node/v4.2.6/lib/node_modules/generator-confit/node_modules/yeoman-generator/lib/base.js:436:25)
    at /Users/timweightman/.nvm/versions/node/v4.2.6/lib/node_modules/generator-confit/node_modules/yeoman-generator/node_modules/run-async/index.js:24:25
    at /Users/timweightman/.nvm/versions/node/v4.2.6/lib/node_modules/generator-confit/node_modules/yeoman-generator/lib/base.js:446:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by uglow** [comment]
Thanks for volunteering - if you could look at implementing a React Sample App (and the Webpack config changes required to build it), that would be fantastic :smiley:

**Comment by uglow** [comment]
This will be fixed when React is added as an option. Closing for now
