### ISSUE TITLE
No files being generated

### ISSUE THREAD

**Issue by tiddle** [odecee/generator-confit#30]
Installed the latest confit, getting an issue where nothing is being generator.

A warning does pop up about a EventEmitter memory leak.

If i run the below using Cmder, it exits out to prompt with no files generated.
If i run the below using git bash, it hangs at "Writing Webpack sampleApp options" 

Here is the Cli output:

```
Confit App Generator
? Choose a build-profile for your project: Webpack - Webpack-based build profile (23 Dec 2015)
? Supported browsers (required) Latest Versions (major browsers)
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Queue.addListener (events.js:239:17)
    at Queue.once (events.js:265:8)
    at run (C:\Users\carlocr\AppData\Roaming\npm\node_modules\generator-confit\node_modules\yeoman-generator\lib\base.js:413:20)
    at composeWith (C:\Users\carlocr\AppData\Roaming\npm\node_modules\generator-confit\node_modules\yeoman-generator\lib\base.js:636:15)
    at C:\Users\carlocr\AppData\Roaming\npm\node_modules\generator-confit\generators\app\index.js:137:12
    at Array.forEach (native)
    at module.exports.confitGen.create.prompting.promptForEverything.profileDescriptions.configuring (C:\Users\carlocr\AppData\Roaming\npm\node_modules\generator-confit\generators\app\index.js:136:43)
    at Object.<anonymous> (C:\Users\carlocr\AppData\Roaming\npm\node_modules\generator-confit\node_modules\yeoman-generator\lib\base.js:436:25)
    at C:\Users\carlocr\AppData\Roaming\npm\node_modules\generator-confit\node_modules\run-async\index.js:26:25
    at C:\Users\carlocr\AppData\Roaming\npm\node_modules\generator-confit\node_modules\run-async\index.js:25:19
Project Path Generator
? Use default/existing paths? Yes
Build CSS Generator
? CSS source format: stylus
Build JS Generator
? Source code language: ES6
? Target output language: ES5
? JavaScript Framework (optional)
? Vendor scripts OR module-names to include (edit in confit.json):
Build HTML Generator
? HTML source file extension? .html
Entry Point Generator
? Entry-points for the application (edit in confit.json):
Dev Server Generator
? Server port: 3000
? Server hostname: localhost
? Server protocol: https
Production Server Generator
? Server port: 3000
? Server hostname: localhost
? Server protocol: https
Release Generator
? Where will this project be hosted? GitHub
? Use semantic releasing? Yes
? Commit message format: Conventional
Verify Generator
? JavaScript coding standard: none
Sample App Generator
? Create a sample app? Yes
Writing Webpack app options
Writing Webpack buildAssets options
Writing Webpack buildCSS options
Writing Webpack buildJS options
Writing Webpack buildHTML options
Writing Webpack build options
Writing Webpack serverDev options
Writing Grunt serverProd options
Writing Webpack unit-test options
Writing Protractor browser-test options
Writing Grunt verify options
Writing NPM release options
Writing Webpack sampleApp options

C:\workspace\confit-test
λ ls -al
total 4
drwxr-xr-x    2  4096 Apr 12 11:50 .
drwxr-xr-x   15 4096 Apr 12 11:35 ..

C:\workspace\confit-test
```

**Comment by uglow** [comment]
Versions of Node, NPM, Yeoman and OS?

**Comment by tiddle** [comment]
I was using an old version of Yo. Updated and passed where it hanged.
